### ISSUE TITLE
MediaPlayerDevice is deprecated (0.11x)

### ISSUE THREAD

**Issue by kaizersoje** [macbury/ha_samsung_multi_room#7]
I get this issue in the logs. It seems that since HA core version 0.11x introduced some breaking changes and this component is affected:
`MediaPlayerDevice is deprecated, modify MultiRoomDevice to extend MediaPlayerEntity`

**Comment by IDmedia** [comment]
This does not seem to be maintained anymore, so I forked it if anyone is interested in an updated version:
https://github.com/IDmedia/hass-samsung_soundbar

**Comment by kaizersoje** [comment]
> This does not seem to be maintained anymore, so I forked it if anyone is interested in an updated version:
> https://github.com/IDmedia/hass-samsung_soundbar

Thanks. There seems to be another one out there as well. [https://github.com/dariornelas/ha_samsung_multi_room](https://github.com/dariornelas/ha_samsung_multi_room)

**Comment by kaizersoje** [comment]
> This does not seem to be maintained anymore, so I forked it if anyone is interested in an updated version:
> https://github.com/IDmedia/hass-samsung_soundbar

There seems to be another one out there. [https://github.com/dariornelas/ha_samsung_multi_room](https://github.com/dariornelas/ha_samsung_multi_room)

**Comment by dariornelas** [comment]
@macbury is maintaining the component in another repo 
check this issue: https://github.com/macbury/ha_samsung_multi_room/issues/5#issuecomment-517147400
